NUMERICAL_COLUMNS:
  - Loan_Amount_Term
  - total_income
  - payment
  - debt_income

CATEGORICAL_COLUMNS:
  - Gender
  - Married
  - Dependents
  - Education
  - Self_Employed
  - Property_Area
  - Credit_History

MODEL_NAME:
  loan-prediction-model.pkl

CAT_ENCODER:
  loan-prediction-encoder.pkl

NUM_SCALER:
  loan-prediction-scaler.pkl

