kind: pipeline
type: docker
name: default

steps:
  - name: setup-environment
    image: python:3.9-slim
    commands:
      - echo "Setting up environment"
      - pip install -r train/src/requirements.txt

  - name: lint
    image: python:3.9-slim
    commands:
      - echo "Running lint checks"
      - pip install flake8
      - flake8 train/src/

  - name: test
    image: python:3.9-slim
    commands:
      - echo "Running tests"
      - pip install pytest
      - pytest train/src/tests/

  - name: build
    image: python:3.9-slim
    commands:
      - echo "Building the project"
      - python train/src/main.py

trigger:
  branch:
    - main
