TARGET:
  Loan_Status

NUMERICAL_COLUMNS:
  - Loan_Amount_Term
  - Total_Income
  - Payment
  - Debt_Income

CATEGORICAL_COLUMNS:
  - Gender
  - Married
  - Dependents
  - Education
  - Self_Employed
  - Property_Area
  - Credit_History

MODEL_NAME:
  Loan_Prediction_Model.pkl

MODEL_BUCKET:
  jibbs-models


